### ISSUE TITLE
Inconsistency on the number of spins in core python interface

### ISSUE THREAD

**Issue by mullzhang** [OpenJij/OpenJij#166]
Following the tutorial on classical ising model (https://openjij.github.io/OpenJijTutorial/build/html/ja/A003-LargeScaleMC.html),
 I executed this program (using openjij==0.1.1 and numpy==1.19.1):

```python
import numpy as np
import cxxjij.graph as G
import cxxjij.system as S

N = 100
graph = G.Dense(N)

mu, sigma = 0, 1

for i in range(N):
    for j in range(N):
        # to avoid a large Jij value, normalize in 1/N
        graph[i,j] = 0 if i == j else np.random.normal()/N

for i in range(N):
    graph[i] = np.random.normal()/N

spin = graph.gen_spin()
mysystem = S.make_classical_ising(spin, graph)
```

Then, I noticed that the number of spins generated at random does not match the number of spins the system has.

```python
print(len(spin), mysystem.num_spins, graph.size())
>>> 100 100 100

print(mysystem.spin.shape)
>>> (101,)
```

**Comment by j-i-k-o** [comment]
Thanks for the issue.

The reason is that the spins in the system `cxxjij.ClassicalIsing` have an auxiliary spin.
For example, if we deal with the classical Ising system with the number of spins 100, we can convert the original Ising model to the equivalent one without any longitudinal fields by adding an auxiliary spin (100 + 1 = 101 spins), which makes the Monte-Carlo calculation more efficiently since all calculations can be reduced to matrix multiplications.

In fact, direct access to the built-in variables of the system (such as `mysystem.spin`) is not recommended except for those who understand the implementation of the system.

It is recommended to get the information of the spins via `cxxjij.result.get_solution()`.

**Comment by j-i-k-o** [comment]
But I understand the current implementation is rather non-user-friendly.
@mullzhang If possible, I would be happy to hear for what purpose you are going to use cxxjij interface directly! I'll use your feedback as a reference for the following versions.

**Comment by mullzhang** [comment]
Thanks for the reply.

I understand its implementation. I thought about the possibility of some kind of transformation by an auxiliary spin, but I didn't know much about it. I thought it would be nice if there was an explanation about it in the documentation or docstring.

This issue is not directly related to the purpose of using cxxjij. I will be using the cxxjij solver and other solvers to evaluate their performance for the same run time. Specifically, I use a callback function that can be used in the core python interface to get information during execution.
